# Generated by Django 5.2.7 on 2025-10-31 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='客戶名稱')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='聯絡電話')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='電子郵件')),
                ('status', models.CharField(choices=[('lead', '潛在客戶'), ('active', '活躍客戶'), ('inactive', '非活躍客戶'), ('archived', '已歸檔')], default='lead', max_length=10, verbose_name='客戶狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新')),
                ('sales_rep', models.ForeignKey(help_text='負責跟進此客戶的系統使用者', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='負責業務員')),
            ],
            options={
                'verbose_name': '客戶',
                'verbose_name_plural': '客戶',
                'ordering': ['name'],
            },
        ),
    ]
